#!/bin/bash

#################################################################
# concatenate MDeNM trajectories
# generated by NAMD
# by Mauricio Costa 
#################################################################

# reference structure
ref='step4_equilibration.coor'
echo "How many replicas ? "
read tot
#"name of the segment containing protein atoms"
seg='PROA'
# write reference file for protein atoms
grep ${seg} ${ref} > ref_prot.pdb

# generate index for protein atoms
grep ${seg} ${ref} | awk '{print $2-1}' > index-prot.txt
echo 'wrote index-prot.txt'

beg=1
a=`echo $PWD` 

for i in `seq ${beg} ${tot}`
do
catdcd -o rep_${i}_prot.dcd -otype dcd -i index-prot.txt -pdb ./${i}/cycle_?.coor ./${i}/cycle_??.coor
#catdcd -o rep_${i}_ca.dcd -otype dcd -i index-ca.txt -pdb ./${i}/cycle_?.coor ./${i}/cycle_??.coor
done
