#!/bin/bash

#################################################################
# concatenate MDeNM trajectories
# generated by NAMD
# by Mauricio Costa 
#################################################################

# reference structure
ref='step4_equilibration.coor'
#echo "How many replicas ? "
tot=100
#read tot
#"name of the segment containing protein atoms"
seg='PROA'
# write reference file for protein atoms

# generate index for protein atoms
grep ' CA ' ${ref} | awk '{print $2-1}' > index-ca.txt
echo 'wrote index_ca'

beg=1
a=`echo $PWD` 

for i in `seq ${beg} ${tot}`
do
./catdcd -o rep_${i}_prot_ca.dcd -otype dcd -i index-ca.txt -pdb ./${i}/cycle_1.coor ./${i}/cycle_2.coor ./${i}/cycle_3.coor ./${i}/cycle_4.coor ./${i}/cycle_5.coor ./${i}/cycle_6.coor ./${i}/cycle_7.coor ./${i}/cycle_8.coor ./${i}/cycle_9.coor ./${i}/cycle_10.coor
done
